name: Update Buffet Data
on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install requests
      - name: Run fetch script
        run: python fetch_all_data.py
      - name: Commit and push JSON
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git add buffet_data.json
          git commit -m "Auto-update buffet data" || echo "No changes to commit"
          git push
